---
title: "Dashboard"
output: 
   flexdashboard::flex_dashboard:
   orientation: columns
   vertical_layout: fill
   code_folding: hide 
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r, include=FALSE}
data(instacart) 

instacart =  
  sample_n(instacart, 20000) %>% 
  mutate(
    order_dow = recode(
      order_dow,
      '0' = "Sunday",
      '1' = "Monday",
      '2' = "Tuesday",
      '3' = "Wednesday",
      '4' = "Thursday",
      '5' = "Friday",
      '6' = "Saturday"
    )
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### Barchart

```{r}
x <- list(
  title = "Aisle"
)
y <- list(
  title = "Total Count"
)
instacart %>% 
  group_by(aisle, order_dow) %>% 
  summarise(total = n()) %>% 
  filter(total >100) %>% 
  plot_ly(y = ~total, x= ~aisle, type = "bar",color = ~order_dow) %>%  layout(title = "Total Number of Items from Each Aisle by Week Day",
         xaxis = x, yaxis = y)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Boxplots

```{r}
y <- list(
  title = "Order Hours of the Day"
  
)
instacart %>% 
  plot_ly( y = ~order_hour_of_day, color = ~department, type = "box") %>% 
  layout(title = "Distibutions of Orders Hours of the Day by each Deparment", yaxis = y)
```





### Linegraph 

```{r}
x <- list(
  title = "Product"
)
y <- list(
  title = "Total Count"
)
instacart %>% 
  group_by(product_name) %>% 
  summarise(count = n()) %>% 
  filter(count >= 75) %>% 
  plot_ly(y = ~count, x = ~product_name, type = "scatter", 
          mode= "markers+lines",
          color = I("green")) %>% 
  layout(title = "Products That Have a Count of 75 or More ",
         xaxis = x, yaxis = y)
 
```






